modLoader="javafml"
loaderVersion="[52,)"
license="Apache-2.0"

[[mods]]
modId="areyousure"
version="1.0.1"
displayName="Are You Sure?"
displayTest="IGNORE_ALL_VERSION"
authors="vyrriox"
description='''
Every action asks if you are really sure, then makes you solve a captcha. Breaking a block, opening a chest, attacking, placing: nothing escapes the confirmation.
'''

[[dependencies.areyousure]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.areyousure]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
